---
title: "initialCleaning"
author: "Oliver & Noah"
date: "4/18/2019"
output: html_document
---


```{r}
library(tidyr)
library(dplyr)
library(stringr)
library(RSentiment)
library(SentimentAnalysis)
```

```{r}
#Load in the data from Data.csv
comments <- read.csv("Data03.csv", header = TRUE)
```

```{r}
#Fix formating each of these blocks reformats a specific row, drops all unnecsary information, and removes rows with problematic formatting if necessary.

uncleaned <- comments

  #Author
  out <- separate(uncleaned, Author, into=c("Junk", "Author"), sep= ":" ,extra = "merge")
    out <- select(out, -Junk)
  out <- out[!is.na((out$Author)),]#Removes another set of slightly malformated rows.
  
  #Author_Flair_CSS_Class
  out <- separate(out, Author_Flair_CSS_Class, into=c("Junk", "Author_Flair_CSS_Class"), sep= ":" ,extra = "merge")
      
    out <- (select(out, -Junk))
  out <- out[!is.na((out$Author_Flair_CSS_Class)),]
  
  #Author_Flair_Text
  out <- separate(out, Author_Flair_Text, into=c("Junk", "Author_Flair_Text"), sep= ":" ,extra = "merge") 
      out <- select(out, -Junk)
  
  #Body
  out <- separate(out, Body, into=c("Junk", "Body"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Can_Gild
  out <- separate(out, Can_Gild, into=c("Junk", "Can_Gild"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Controversiality
  out <- separate(out, Controversiality, into=c("Junk", "Controversiality"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Distinguished
  out <- separate(out, Distinguished, into=c("Junk", "Distinguished"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Edited
  out <- separate(out, Edited, into=c("Junk", "Edited"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Gilded
  out <- separate(out, Gilded, into=c("Junk", "Gilded"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #ID
  out <- separate(out, ID, into=c("Junk", "ID"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Is_Submitter
  out <- separate(out, Is_Submitter, into=c("Junk", "Is_Submitter"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Link_ID
  out <- separate(out, Link_ID, into=c("Junk", "Link_ID"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Parent_ID
  out <- separate(out, Parent_ID, into=c("Junk", "Parent_ID"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Permalink
  out <- separate(out, Permalink, into=c("Junk", "Permalink"), sep= ":" ,extra = "merge")
      out <- select(out, -Junk)
  
  #Score
  out <- separate(out, Score, into=c("Junk", "Score"), sep= ":" ,extra = "merge")
      select(out, -Junk)
  
  #Stickied
  out <- separate(out, Stickied, into=c("Junk", "Stickied"), sep= ":" ,extra = "merge")
      select(out,-Junk)
  
  #Subreddit
  out <- separate(out, Subreddit, into=c("Junk", "Subreddit"), sep= ":" ,extra = "merge")
      select(out,-Junk)
  
  #Subreddit_ID
  out <- separate(out, Subreddit_ID, into=c("Junk", "Subreddit_ID"), sep= ":" ,extra = "merge")
      select(out,-Junk)
  
  #Subreddit_Type
  out <- separate(out, Subreddit_Type, into=c("Junk", "Subreddit_Type"), sep= ":" ,extra = "merge")
      select(out,-Junk)

comments <- out

```

```{r}
#Remove duplicate rows
comments <- comments[!duplicated(comments),]

#Drop superfluous columns
comments <- subset(comments, select = -c(Author, Create_UTC, ID, Link_ID, Parent_ID, Permalink, Subreddit_ID))

#Convert controversiality and score from char to numeric
comments <- comments %>% 
  mutate(Controversiality = as.numeric(Controversiality),
         Score = as.numeric(Score),
         id = row_number())
```

## Functions to add sentiment analysis to data frame
```{r}

create_subset <- function(df, subset_bottom, subset_top) {
  
  subset <- df %>% 
    filter(id > subset_bottom & id <= subset_top)
  
  comments_temp <- analyzeSentiment(subset$Body) %>% 
    mutate(id = row_number() + subset_bottom)

  df_subset <- full_join(subset, comments_temp, by="id")
  
  return(df_subset)
}

create_full_df <- function(df) {
  df1 <- create_subset(df, 0, 20000)
  df2 <- create_subset(df, 20000, 40000)
  df3 <- create_subset(df, 40000, 60000)
  df4 <- create_subset(df, 60000, 80000)
  df5 <- create_subset(df, 80000, 99500)
  
  final_df <- full_join(df1, df2)
  final_df <- full_join(final_df, df3)
  final_df <- full_join(final_df, df4)
  final_df <- full_join(final_df, df5)
  
  return(final_df)
}

# this takes a long time
final_df <- create_full_df(comments)
```

## Now write final dataframe to a csv
```{r}
write.csv(final_df, file = "finalData03.csv")
```
