---
title: "R Notebook"
output: html_notebook
---



```{r}
library(dplyr)
library(mosaic)
library(DescTools)
library(lmtest)
library(knitr)
```


```{r}


fullComments <- read.csv("fullComments.csv")

#filtering the data 
controversial <- fullComments %>% 
  filter(Controversiality == 1)

noncontroversial <- fullComments %>% 
  filter(Controversiality != 1) 

n <-  sample(noncontroversial$X, size = 9064, replace = FALSE)

sampled_noncontroversial <- noncontroversial %>% 
  filter(noncontroversial$X  %in%  n)

sampled_data <- rbind(controversial, sampled_noncontroversial)


```


```{r}
kitchenSink <- glm(Controversiality ~ WordCount + Gilded + WKND + Moderator + comments_in_subreddit + SentimentQDAP + SentimentGI + SentimentLM + SentimentHE + subreddit_scaled_total_mean + subreddit_diff_QDAP + subreddit_diff_LM +  relative_sentiment_diff, data = sampled_data, family = "binomial")

msummary(kitchenSink)

#without gilded
without_gilded <- glm(Controversiality ~ WordCount + WKND + Moderator + comments_in_subreddit + SentimentQDAP + SentimentGI + SentimentLM + SentimentHE + subreddit_scaled_total_mean + subreddit_diff_QDAP + subreddit_diff_LM +  relative_sentiment_diff, data = sampled_data, family = "binomial")

msummary(without_gilded)

#without moderator
without_moderator <- glm(Controversiality ~ WordCount + WKND + comments_in_subreddit + + SentimentQDAP + SentimentGI + SentimentLM + SentimentHE + subreddit_scaled_total_mean + subreddit_diff_QDAP + subreddit_diff_LM +  relative_sentiment_diff, data = sampled_data, family = "binomial")

msummary(without_moderator)

#without insignificant 
without_insig <- glm(Controversiality ~ WordCount + WKND + comments_in_subreddit + SentimentQDAP + SentimentGI + subreddit_scaled_total_mean + subreddit_diff_QDAP + subreddit_diff_LM +  relative_sentiment_diff, data = sampled_data, family = "binomial")

msummary(without_insig)

#final1
final1 <- glm(Controversiality ~ WordCount + WKND + comments_in_subreddit + SentimentQDAP + SentimentGI + subreddit_scaled_total_mean + subreddit_diff_QDAP , data = sampled_data, family = "binomial")

msummary(final1)
lrtest(final1, without_insig)

wordcount_only <- glm(Controversiality ~WordCount, data=sampled_data, family="binomial")
msummary(wordcount_only)

sentiment_only <- glm(Controversiality ~ WordCount+ SentimentQDAP + subreddit_scaled_total_mean + subreddit_diff_QDAP, data=sampled_data, family="binomial")

msummary(sentiment_only)
accuracy(sentiment_only)

sentiment_only2 <- glm(Controversiality ~  SentimentQDAP + subreddit_scaled_total_mean + subreddit_diff_QDAP, data=sampled_data, family="binomial")

subreddit_only <- glm(Controversiality ~ subreddit_scaled_total_mean, data=sampled_data, family = "binomial")


msummary(sentiment_only2)
msummary(subreddit_only)
accuracy(subreddit_only)

wordcount_only <- glm(Controversiality ~WordCount, data=sampled_data, family="binomial")
msummary(wordcount_only)
#intercerpt only
intercept_only <- glm(Controversiality~ 1, data = sampled_data, family = "binomial")
msummary(intercept_only)
```

### MAKE FUNCTION
```{r}
my.expit <- function(x) {
  y <- exp(x) / (1+exp(x))
  return(y)
}

accuracy <- function(model) {
  
  #sample from the noncontroversial comments to make a dataset
  n <-  sample(noncontroversial$X, size = 9064, replace = FALSE)

  sampled_noncontroversial <- noncontroversial %>% 
    filter(noncontroversial$X  %in%  n)

  sampled_data <- rbind(controversial, sampled_noncontroversial)
  
  #sample the sampled_data set to make train and testing set
  filtered <- sampled_data

  randomnums <- filtered %>%
   mutate(randomnum = rnorm(nrow(filtered))) %>%
   arrange(randomnum) 
  
  train.set <- randomnums[1:9064,]

  test.set <- randomnums[9065:18128,]
  
  predictions <- test.set %>% 
  mutate(predicted.logodds = predict(model, newdata = test.set),
         
         predicted.prob2 = my.expit(predicted.logodds),
         
         # change the cutoff HERE
         classified.outcome = ifelse(predicted.prob2 > 0.5, yes=1, no=0))

  acc <- (tally(Controversiality ~ classified.outcome, data = predictions)[1,1] + 
            tally(Controversiality ~ classified.outcome, data = predictions)[2,2]) /
      sum(tally(Controversiality ~ classified.outcome, data = predictions))
  
  return(acc)
}
```



```{r}
accuracy(final1)
accuracy(without_insig)
accuracy(kitchenSink)
accuracy(without_gilded)
accuracy(without_moderator)
accuracy(wordcount_only)

final1_dist <- do(100)*accuracy(final1)
gf_density(~accuracy, data=final1_dist)
a<- mean(final1_dist$accuracy)

insig_dist <- do(100)*accuracy(without_insig)
b <- mean(insig_dist$accuracy)

sink_dist <- do(100)*accuracy(kitchenSink)
c <- mean(sink_dist$accuracy)

wo_gilded <- do(100)*accuracy(without_gilded)
d<- mean(wo_gilded$accuracy)

wo_moderator <- do(100)*accuracy(without_moderator)
e<-mean(wo_moderator$accuracy)

sentiment_dist <- do(100)*accuracy(sentiment_only)
f<-mean(sentiment_dist$accuracy)

subreddit_dist <- do(100)*accuracy(subreddit_only)
g<-mean(subreddit_dist$accuracy)

sentiment_dist2 <- do(100)*accuracy(sentiment_only2)
h<-mean(sentiment_dist2$accuracy)


results<- c(a,b,c,d,e,f)
kable(results)
```


