---
title: "Scratchwork"
author: "Oliver"
date: "4/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSentiment)
library(SentimentAnalysis)
library(dplyr)
```

## RSentiment Package

```{r}
test <- calculate_sentiment(c("hello how are you you fucker", "you look so good today", "I love you", "I hate hate hate hate hate you", "hello how are you you fucker", "Aw yeah incest is illegal. Jerking off in the same room with a guy who happens to be your cousin is not illegal. Weird, maybe. But illegal, no. Get your facts right idiot")) 

titest <- test %>% 
  select(text)

final_data <- test %>% 
  mutate(FinalSentiment = calculate_sentiment(text)$sentiment)

View(final_data)
```

## SentimentAnalsyis package

```{r}
# sentiment <- analyzeSentiment("Yeah, this was a great soccer game for the  German team!")
# convertToBinaryResponse(sentiment)$SentimentQDAP

documents <- data.frame("text" = c(
                "Wow, I really like the new light sabers!",
               "That book was excellent.",
               "R is a fantastic language.",
               "The service in this restaurant was miserable.",
               "This is neither positive or negative.",
               "The waiter forget about my dessert -- what poor service!"),
               "id" = c(1,2,3,4,5,6)) %>% 
  mutate(text = as.character(text),
         sentiment = convertToBinaryResponse(analyzeSentiment(text)$SentimentQDAP))

sentiment <- analyzeSentiment(documents$text) %>% 
  mutate(id = row_number())

convertToBinaryResponse(sentiment)$SentimentQDAP

final_df <- full_join(documents, sentiment, by="id")

```

